// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeohLHeLpQqzTB7gRMF0jPVBTU4eyLn5Y',
    appId: '1:653474732813:web:58595b5885a20a7072ae44',
    messagingSenderId: '653474732813',
    projectId: 'calocam-a385d',
    authDomain: 'calocam-a385d.firebaseapp.com',
    storageBucket: 'calocam-a385d.firebasestorage.app',
    measurementId: 'G-14Y5PLBCCT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDCK2rutTBSRZ5Q_kC1vyg5-lsZATZHOo',
    appId: '1:653474732813:android:f5120445319f314972ae44',
    messagingSenderId: '653474732813',
    projectId: 'calocam-a385d',
    storageBucket: 'calocam-a385d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy9a-EGD4TylbWMa-MedFbZ5OYTpzEkPs',
    appId: '1:653474732813:ios:13ca856cd715f74672ae44',
    messagingSenderId: '653474732813',
    projectId: 'calocam-a385d',
    storageBucket: 'calocam-a385d.firebasestorage.app',
    iosClientId: '653474732813-prqn5khaadbk3gd4hqogajce8jnqbfaf.apps.googleusercontent.com',
    iosBundleId: 'com.example.calocountApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy9a-EGD4TylbWMa-MedFbZ5OYTpzEkPs',
    appId: '1:653474732813:ios:13ca856cd715f74672ae44',
    messagingSenderId: '653474732813',
    projectId: 'calocam-a385d',
    storageBucket: 'calocam-a385d.firebasestorage.app',
    iosClientId: '653474732813-prqn5khaadbk3gd4hqogajce8jnqbfaf.apps.googleusercontent.com',
    iosBundleId: 'com.example.calocountApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeohLHeLpQqzTB7gRMF0jPVBTU4eyLn5Y',
    appId: '1:653474732813:web:20649a82e54ec82672ae44',
    messagingSenderId: '653474732813',
    projectId: 'calocam-a385d',
    authDomain: 'calocam-a385d.firebaseapp.com',
    storageBucket: 'calocam-a385d.firebasestorage.app',
    measurementId: 'G-2WB0Q8BJ3Z',
  );
}
